### ISSUE TITLE
Documentation website not working

### ISSUE THREAD

**Issue by HtetOoWaiYan** [digiaonline/react-foundation#118]
### What did you do?
I go to https://digia.online/react-foundation-docs/.

### What did you expect to happen?
I expected a working site.

### What actually happened?
It showed "404 There isn't a GitHub Pages site here".

<img width="870" alt="Screen Shot 2021-09-23 at 6 15 02 PM" src="https://user-images.githubusercontent.com/25116846/134501330-04d0aaf3-e456-48a6-9d83-e279b1445746.png">

**Comment by hugovk** [comment]
Thanks for the report, we'll take a look. 

In the meantime, you can see the docs at https://digiaonline.github.io/react-foundation-docs/

**Comment by hugovk** [comment]
OK should be sorted now!

---

The `digia.online` recently expired and was renewed, and it seems GitHub Pages had unlinked from it.

The fix was to go to the top-level repo (https://github.com/digiaonline/digiaonline.github.io/settings/pages), switch the branch from `master` to a temporary branch (from `master`) and then switch it back.

![image](https://user-images.githubusercontent.com/1324225/134506194-dd5f957e-1038-415c-a229-c70bff66600a.png)

It then picked up the `CNAME` containing `digia.online` and re-linked the pages to their URLs.

https://github.com/digiaonline/digiaonline.github.io/blob/master/CNAME

Thanks again!
