### ISSUE TITLE
Foundation Utils

### ISSUE THREAD

**Issue by froger** [digiaonline/react-foundation#47]
Hello,
Thanks for this lib, awesome work ! 
I am starting to code the foundation [off-canvas component](http://foundation.zurb.com/sites/docs/off-canvas.html), but I am bit confused on how to start. 

As I understood while reading [the _Slider, Tooltip, Reveal, other JS Components_ issue](https://github.com/digiaonline/react-foundation/issues/6#issuecomment-199370665)'s comments, the lib should re-code the JS Components without any JQuery dependency. My problem is that in the case off the off-canvas, the component make use of [keyboard](http://foundation.zurb.com/sites/docs/javascript-utilities.html#keyboard) and [media query](http://foundation.zurb.com/sites/docs/javascript-utilities.html#mediaquery) javascript utilities. And sadly both of them use a JQuery dependency. 

Even it can be fast to drop the jquery depencencies (use only `$.find`, `$.on`, `$.off`) to make a vanilla dependency, should'nt it easier to rely on some well-tested vanilla libraries for foundation.utils.* ?

**Comment by crisu83** [comment]
The problem with using existing utils written with jQuery is the performance and the anti-pattern of using DOM manipulation libraries together with React. This is exactly the reason why we havn't implemented these features. I actually gave the approach a try long ago but abandoned it quickly because it promoted bad design.

Feel free to use whatever libraries you want, but remember that even though you can use jQuery together with React they don't play that well together. However, depending on your use-case what you are suggested could be a viable short-term solution.

**Comment by froger** [comment]
thanks for your response, I understand you don't want jquery on the project, and I think it's a good idea. 
However if you don't want to have any vanilla javascript library, you will have to re-implement libs like [imagesloaded](https://imagesloaded.desandro.com/) or [bean](https://github.com/fat/bean). Dependencies not always promote bad design ;)

**Comment by crisu83** [comment]
@froger I agree. We also try to keep the dependencies to the minimum. Just try to avoid DOM manipulation libraries if you can. 

Just remember to check if you can use VanillaJS on caniuse.com if you only have to support the two latest version of each browser. Sometimes you'll be surprised how easy the solution can be.
